BTN_DE/BTN_DE/Controllers/Admin/AdminUserManagerController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BTN_DE.Lib;
using BTN_DE.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace BTN_DE.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminUserManagerController : Controller
    {
        public AdminUserManagerController()
        {
        }

        public AdminUserManagerController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public static int DefaultPageItems = 10;

        //
        // GET: /Users/
        public async Task<ActionResult> Index(UserIndexViewModel model, string pageNumber = "1")
        {
            var users = await UserManager.Users.ToListAsync();
            users = users.OrderByDescending(x => x.RegisterDate).Reverse().ToList();

            if (model == null)
            {
                model = new UserIndexViewModel();
            }

            if (!string.IsNullOrEmpty(pageNumber))
            {
                int pageNum;
                if (int.TryParse(pageNumber, out pageNum))
                {
                    model.PagingInformation = PagingHelper<ApplicationUser>.
                        Paging(DefaultPageItems, "../AdminUserManager/Index?pageNumber=", pageNum, users);
                }
            }

            return View(model);
        }

        //
        // GET: /Users/Details/
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            UserDetailsViewModel model = new UserDetailsViewModel
            {
                Id = user.Id,
                Username = user.UserName,
                Email = user.Email,
                EmailConfirmed = user.EmailConfirmed,
                RegisterDate = user.RegisterDate,
                Name = user.Name,
                Gender = user.Gender,
                Birthday = user.Birthday,
                Address = user.Address,
                PhoneNumber = user.PhoneNumber
            };

            return View(model);
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = userViewModel.Username, 
                    Email = userViewModel.Email,
                    RegisterDate = DateTime.Now
                };

                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            EditUserViewModel model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                }),
                Name = user.Name,
                Gender = 2,
                Birthday = user.Birthday,
                Address = user.Address,
                PhoneNumber = user.PhoneNumber
            };

            if (user.Gender)
            {
                model.Gender = 1;
            }

            return View(model);
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.Email = editUser.Email;
                user.EmailConfirmed = false;
                user.Name = editUser.Name;
                user.Gender = editUser.Gender == 1;

                user.Birthday = editUser.Birthday;
                user.Address = editUser.Address;
                user.PhoneNumber = editUser.PhoneNumber;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            DeleteUserViewModel model = new DeleteUserViewModel
            {
                Id = user.Id,
                Username = user.UserName,
                Email = user.Email,
                ErrorMessage = ""
            };

            if (id == User.Identity.GetUserId())
            {
                model.ErrorMessage = "Bạn không thể xóa người dùng hiện tại, hãy đăng xuất và đăng nhập vào tài khoản khác để thực hiện";
            }

            return View(model);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

BTN_DE/BTN_DE/Views/AdminUserManager/Create.cshtml
@model BTN_DE.Models.RegisterViewModel
@{
    ViewBag.Title = "Tạo tài khoản";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>

<div class="container">
    <div class="form_addproduct col-sm-8">
        @using (Html.BeginForm("Create", "AdminUserManager",
            FormMethod.Post, new {enctype = "multipart/form-data", @class = "createform row", data_validatable = true}))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new {@class = "text-error"})
            <h4>Tạo một tài khoản mới.</h4>
            <fieldset>
                <div class="row form_addproduct_child">
                    <div class="editor-label col-sm-4">
                        @Html.LabelFor(model => model.Username)
                    </div>
                    <div class="editor-field col-sm-9">
                        @Html.EditorFor(model => model.Username)
                        @Html.ValidationMessageFor(model => model.Username)
                    </div>
                </div>

                <div class="row form_addproduct_child">
                    <div class="editor-label col-sm-4">
                        @Html.LabelFor(model => model.Password)
                    </div>
                    <div class="editor-field col-sm-9">
                        @Html.EditorFor(model => model.Password)
                        @Html.ValidationMessageFor(model => model.Password)
                    </div>
                </div>

                <div class="row form_addproduct_child">
                    <div class="editor-label col-sm-9">
                        @Html.LabelFor(model => model.ConfirmPassword)
                    </div>
                    <div class="editor-field col-sm-9">
                        @Html.EditorFor(model => model.ConfirmPassword)
                        @Html.ValidationMessageFor(model => model.ConfirmPassword)
                    </div>
                </div>

                <div class="row form_addproduct_child">
                    <div class="editor-label col-sm-4">
                        @Html.LabelFor(model => model.Email)
                    </div>
                    <div class="editor-field col-sm-9">
                        @Html.EditorFor(model => model.Email)
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>

                <div class="row form_addproduct_child">
                    <div class="editor-label col-sm-4">
                        @Html.LabelFor(model => model.ConfirmEmail)
                    </div>
                    <div class="editor-field col-sm-9">
                        @Html.EditorFor(model => model.ConfirmEmail)
                        @Html.ValidationMessageFor(model => model.ConfirmEmail)
                    </div>
                </div>

                <div class="form-group">
                    <div class="editor-label col-sm-4">
                        <label>
                            Chọn vài trò cho tài khoản
                        </label>
                    </div>
                    <div class="col-md-10">
                        @foreach (var item in (SelectList) ViewBag.RoleId)
                        {
                            <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline"/>
                            @Html.Label(item.Value, new {@class = "control-label"})
                        }
                    </div>
                </div>

                <div class="form-group">
                    <div class="editor-field col-sm-9">
                        <input type="submit" value="Hoàn thành"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="editor-field col-sm-9">
                        @Html.ActionLink("Trở lại", "Index")
                    </div>
                </div>
            </fieldset>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTN_DE/BTN_DE/Views/AdminUserManager/Delete.cshtml
@model BTN_DE.Models.DeleteUserViewModel

@{
    ViewBag.Title = "Xóa tài khoản";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>

<h3>Bạn có chắc là muốn xóa người dùng này?</h3>
<div>
    <h4>Người dùng.</h4>
    <hr />
    <dl class="dl-horizontal">

        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <dt>
                @Html.LabelFor(model => model.ErrorMessage)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ErrorMessage)
            </dd>
        }

        <dt>
            @Html.LabelFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Username)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div>
                @Html.ActionLink("Trở lại", "Index")
            </div>
        }
        else
        {
            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-default"/>
            </div>
            <div>
                @Html.ActionLink("Trở lại", "Index")
            </div>
        }
    }
</div>

BTN_DE/BTN_DE/Views/AdminUserManager/Details.cshtml
@model BTN_DE.Models.UserDetailsViewModel
@{
    ViewBag.Title = "Thông tin chi tiết";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>

<div>
    <h4>Người dùng</h4>
    <hr/>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.Id)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.Id)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.Username)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.Username)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.Email)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.EmailConfirmed)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.EmailConfirmed)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.RegisterDate)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.RegisterDate)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.Gender)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.Gender)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.Birthday)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.Birthday)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.Address)
        </div>
    </div>

    <div class="row form_addproduct_child">
        <div class="editor-label col-sm-4">
            @Html.LabelFor(model => model.PhoneNumber)
        </div>
        <div class="editor-field col-sm-9">
            @Html.DisplayFor(model => model.PhoneNumber)
        </div>
    </div>
</div>
<h4>Danh sách các người dùng với vai trò</h4>
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>Không có người dùng nào với vai trò này.</p>
}

<table class="table">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.Id }) | @Html.ActionLink("Trở lại", "Index")
</p>

BTN_DE/BTN_DE/Views/AdminUserManager/Edit.cshtml
@model BTN_DE.Models.EditUserViewModel

@{
    ViewBag.Title = "Sửa thông tin người dùng";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Mẫu sửa thông tin.</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="row form_addproduct_child">
            <div class="editor-label col-sm-4">
                @Html.LabelFor(model => model.Email)
            </div>
            <div class="editor-field col-sm-9">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="row form_addproduct_child">
            <div class="editor-label col-sm-4">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field col-sm-9">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="row form_addproduct_child">
            <div class="editor-label col-sm-4">
                @Html.LabelFor(model => model.Gender)
            </div>
            <div class="editor-field col-sm-9">
                @Html.DropDownListFor(model => model.Gender, Model.GenderList)
                @Html.ValidationMessageFor(model => model.Gender)
            </div>
        </div>

        <div class="row form_addproduct_child">
            <div class="editor-label col-sm-4">
                @Html.LabelFor(model => model.Birthday)
            </div>
            <div class="editor-field col-sm-9">
                @Html.EditorFor(model => model.Birthday)
                @Html.ValidationMessageFor(model => model.Birthday)
            </div>
        </div>

        <div class="row form_addproduct_child">
            <div class="editor-label col-sm-4">
                @Html.LabelFor(model => model.Address)
            </div>
            <div class="editor-field col-sm-9">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="row form_addproduct_child">
            <div class="editor-label col-sm-9">
                @Html.LabelFor(model => model.PhoneNumber)
            </div>
            <div class="editor-field col-sm-9">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>

        <div class="form-group">
            <div class="editor-label col-sm-4">
                <label>
                    Vai trò
                </label>
            </div>
            <div class="col-md-10">
               @foreach (var item in Model.RolesList)
               {
                <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
               }
            </div>
        </div>

        <div class="form-group">
            <div class="editor-field col-sm-9">
                <input type="submit" value="Lưu thay đổi"/>
            </div>
        </div>
        <div class="form-group">
            <div class="editor-field col-sm-9">
                @Html.ActionLink("Trở lại", "Index")
            </div>
        </div>      
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTN_DE/BTN_DE/Views/AdminUserManager/Index.cshtml
@model BTN_DE.Models.UserIndexViewModel

@{
    ViewBag.Title = "Danh sách tài khoản";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>

<div class="btn-toolbar list-toolbar">
    <button class="btn btn-primary" onclick=" location.href = '../AdminUserManager/Create'; ">
        <i class="fa fa-plus"></i>Tài khoản mới
    </button>
    <div class="btn-group">
    </div>
</div>

<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Tên tài khoản</th>
        <th>Email</th>
        <th>Ngày tạo</th>
        <th style="width: auto;"></th>
    </tr>
    </thead>

    <tbody>
    @{
        for (int i = 0; i < Model.PagingInformation.Items.Count; i++)
        {
            <tr>
                @{
                    var user = Model.PagingInformation.Items[i];
                }
                <td>@((i + 1).ToString())</td>
                <td>@user.UserName.Trim()</td>
                <td>@user.Email.Trim()</td>
                <th>@user.RegisterDate</th>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new {id = user.Id}) |
                    @Html.ActionLink("Chi tiết", "Details", new {id = user.Id}) |
                    @Html.ActionLink("Xóa", "Delete", new {id = user.Id})
                </td>
            </tr>
        }
    }
    </tbody>
</table>

@Html.Raw(Model.PagingInformation.PaginationHtml)