BTN_DE/BTN_DE/Controllers/Admin/AdminRoleManagerController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BTN_DE.Lib;
using BTN_DE.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace BTN_DE.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminRoleManagerController : Controller
    {
        public AdminRoleManagerController()
        {
        }

        public AdminRoleManagerController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public static int DefaultPageItems = 10;

        // GET: AdminRoleManager
        public ActionResult Index(RoleIndexViewModel model, string pageNumber = "1")
        {
            var roles = RoleManager.Roles.ToList();
            if (model == null)
            {
                model = new RoleIndexViewModel();
            }

            if (!string.IsNullOrEmpty(pageNumber))
            {
                int pageNum;
                if (int.TryParse(pageNumber, out pageNum))
                {
                    model.PagingInformation = PagingHelper<IdentityRole>.Paging(DefaultPageItems, 
                        "../AdminRoleManager/Index?pageNumber=", pageNum, roles);
                }
            }        
            
            return View(model);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }

            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };

            if (role.Name == "Admin")
            {
                roleModel.ErrorMessage = "Quyền admin không thể bị thay đổi.";
            }

            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }

            EditRoleViewModel model = new EditRoleViewModel
            {
                Role = role,
                ErrorMessage = ""
            };

            if (role.Name == "Admin")
            {
                model.ErrorMessage = "Quyền admin không thể bị xóa.";
            }

            return View(model);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

BTN_DE/BTN_DE/Views/AdminRoleManager/Create.cshtml
@model BTN_DE.Models.RoleViewModel

@{
    ViewBag.Title = "Tạo vai trò mới";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vai trò.</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTN_DE/BTN_DE/Views/AdminRoleManager/Delete.cshtml
@model BTN_DE.Models.EditRoleViewModel

@{
    ViewBag.Title = "Xóa vai trò";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>

<h3>Bạn có muốn xóa vai trò này? </h3>
<p>Xóa Vai trò này sẽ loại bỏ tất cả các người dùng từ vai trò này. Nó sẽ không xóa các người sử dụng.</p>
<div>
    <h4>Vai trò.</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <dt>
                @Html.DisplayNameFor(model => model.ErrorMessage)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ErrorMessage)
            </dd>
        }
        
        <dt>
            @Html.DisplayNameFor(model => model.Role.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.Name)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="form-actions no-color">
                @Html.ActionLink("Trở lại", "Index")
            </div>
        }
        else
        {
            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-default" /> |
                @Html.ActionLink("Trở lại", "Index")
            </div>
        }
    }
</div>

BTN_DE/BTN_DE/Views/AdminRoleManager/Details.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Xem chi tiết";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Vai trò.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<h4>Danh sách các người dùng trong vai trò này</h4>
@if (ViewBag.UserCount == 0)
{
    <hr />
    <p>Không có người dùng nào được tìm thấy trong vai trò này.</p>
}

<table class="table">

    @foreach (var item in ViewBag.Users)
    {
        <tr>
            <td>
                @item.UserName
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Trở lại", "Index")
</p>

BTN_DE/BTN_DE/Views/AdminRoleManager/Edit.cshtml
@model BTN_DE.Models.RoleViewModel

@{
    ViewBag.Title = "Sửa vai trò";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>


@using (Html.BeginForm("Edit", "AdminRoleManager",
    FormMethod.Post, new { enctype = "multipart/form-data", @class = "createform row", data_validatable = true }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vai trò.</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="row form_addproduct_child">
                <div class="editor-label col-sm-4">
                    @Html.LabelFor(model => model.ErrorMessage)
                </div>
                <div class="editor-field col-sm-9">
                    @Html.DisplayFor(model => model.ErrorMessage)
                </div>
            </div>

            <div class="row form_addproduct_child">
                <div class="editor-label col-sm-4">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="editor-field col-sm-9">
                    @Html.DisplayFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                <div class="editor-field col-sm-9">
                    @Html.ActionLink("Trở lại", "Index")
                </div>
            </div>
        }
        else
        {
            <div class="row form_addproduct_child">
                <div class="editor-label col-sm-4">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="editor-field col-sm-9">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                <div class="editor-field col-sm-9">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
            <div class="form-group">
                <div class="editor-field col-sm-9">
                    @Html.ActionLink("Trở lại", "Index")
                </div>
            </div>
        }
                  
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BTN_DE/BTN_DE/Views/AdminRoleManager/Index.cshtml
@model BTN_DE.Models.RoleIndexViewModel
@{
    ViewBag.Title = "Danh sách vai trò";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title.</h2>

<div class="btn-toolbar list-toolbar">
    <button class="btn btn-primary" onclick=" location.href = '../AdminRoleManager/Create'; ">
        <i class="fa fa-plus"></i>Vai trò mới
    </button>
    <div class="btn-group">
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Mã số</th>
            <th>Tên</th>
            <th style="width:auto;"></th>
        </tr>
    </thead>

    <tbody>
        @{
            for (int i = 0; i < Model.PagingInformation.Items.Count; i++)
            {
                <tr>
                    @{
                var role = Model.PagingInformation.Items[i];
                    }
                    <td>@((i + 1).ToString())</td>
                    <td>@role.Id.Trim()</td>
                    <td>@role.Name.Trim()</td>
                    <td>
                        @Html.ActionLink("Sửa", "Edit", new { id = role.Id }) |
                        @Html.ActionLink("Chi tiết", "Details", new { id = role.Id }) |
                        @Html.ActionLink("Xóa", "Delete", new { id = role.Id })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

@Html.Raw(Model.PagingInformation.PaginationHtml)